image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - release

variables:
  path: "YoutubeChannelAPI"
  ASPNETCORE_ENVIRONMENT: "Development"
  
before_script:
  - "dotnet restore"

build-dotnet:
  stage: build
  script:
    - "cd $path"
    - "dotnet build"
    - "dotnet restore"

test-dotnet:
  services:
    - name: postgres:16
      alias: db
  variables:
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust
    GITLAB_CONNECTION_STRING: $CONNECTION_STRING
    GITLAB_TEST_CONNECTION_STRING: $TEST_CONNECTION_STRING
  stage: test
  script:
    - "dotnet test"

release-dotnet:
  stage: release
  artifacts:
    paths:
      - publish/
  script:
    - "ls"
    - "dotnet publish -c Release -o ./publish YoutubeChannelAPI/YoutubeChannelAPI.csproj"
    - "ls"
  environment: production